backend:
  name: github
  branch: master
  repo: chrysillala/laku-laku

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }